/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author gabri
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    Color DefaultColor, ClickedColor;

    public FrmInicio() {
        initComponents();

        
        jDesktopPanel.setLayout(new java.awt.BorderLayout());
        DefaultColor = new Color(55, 55, 55);
        ClickedColor = new Color(240, 151, 57);

        //Set default color to pan on run time
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        setTitle("Liberty Networks Caribe | Inicio");
        setResizable(true);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(800, 1020));
        SetImageLabel(jLabel28, "/IMG/Logoliberty.png");
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMG/Splashliberty.png")).getImage());
        CiudadName.setText("...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        CiudadName = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        BtnSIPMEDIA = new javax.swing.JButton();
        BtnVirtualRanges = new javax.swing.JButton();
        BtnVoice = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jPanelJamaica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelTrinidadyTobago = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelSantaLucia = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelBarbados = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelGranada = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelIslasTurcasyCaicos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelIslasCaiman = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelRepublicaDominicana = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelSanVicenteyLasGRN = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelSanCristobalyNieves = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelIslasVirgenesBRT = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelAnguila = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelBahamas = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanelAntiguayBarbuda = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanelMontserrat = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanelAllSIPTrunks = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanelTrunkID = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanelTeams = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanelCMS = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);

                java.net.URL url = getClass().getResource("/IMG/LIBERTY_NETWORKS_MAP.png");
                if (url != null) {
                    java.awt.Image img = new javax.swing.ImageIcon(url).getImage();

                    // Convertimos a Graphics2D para aplicar filtros avanzados de calidad de imagen
                    java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;

                    // FILTROS DE ALTA CALIDAD: Evitan que la imagen se pixele o se vea borrosa al estirarse
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_COLOR_RENDERING, java.awt.RenderingHints.VALUE_COLOR_RENDER_QUALITY);

                    // Dibujamos la imagen forzándola a rellenar el 100% del panel (0, 0, ancho, alto)
                    g2d.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 153, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        CiudadName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CiudadName.setText("Jamaica");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Detalles de lo seleccionado |");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setText("Liberty Networks Caribe | Panel de Consultas");

        BtnVolver.setBackground(new java.awt.Color(153, 153, 153));
        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Iconovolver.png"))); // NOI18N
        BtnVolver.setToolTipText("Quitar Seleccion");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        BtnSIPMEDIA.setBackground(new java.awt.Color(153, 153, 153));
        BtnSIPMEDIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Iconoip.png"))); // NOI18N
        BtnSIPMEDIA.setToolTipText("SIP & Media");
        BtnSIPMEDIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSIPMEDIAMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnSIPMEDIAMousePressed(evt);
            }
        });
        BtnSIPMEDIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSIPMEDIAActionPerformed(evt);
            }
        });

        BtnVirtualRanges.setBackground(new java.awt.Color(153, 153, 153));
        BtnVirtualRanges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Iconorango.png"))); // NOI18N
        BtnVirtualRanges.setToolTipText("Virtual Ranges");
        BtnVirtualRanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnVirtualRangesMousePressed(evt);
            }
        });
        BtnVirtualRanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVirtualRangesActionPerformed(evt);
            }
        });

        BtnVoice.setBackground(new java.awt.Color(153, 153, 153));
        BtnVoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Iconovoice.png"))); // NOI18N
        BtnVoice.setToolTipText("Voice GW");
        BtnVoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVoiceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnVoiceMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnVoice, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnVirtualRanges))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(BtnSIPMEDIA)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CiudadName))
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnVirtualRanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnVoice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnSIPMEDIA, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(CiudadName))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel.setBackground(new java.awt.Color(55, 55, 55));

        jPanelJamaica.setBackground(new java.awt.Color(55, 55, 55));
        jPanelJamaica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelJamaicaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelJamaicaMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JAMAICA");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanelJamaicaLayout = new javax.swing.GroupLayout(jPanelJamaica);
        jPanelJamaica.setLayout(jPanelJamaicaLayout);
        jPanelJamaicaLayout.setHorizontalGroup(
            jPanelJamaicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJamaicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );
        jPanelJamaicaLayout.setVerticalGroup(
            jPanelJamaicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJamaicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTrinidadyTobago.setBackground(new java.awt.Color(55, 55, 55));
        jPanelTrinidadyTobago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTrinidadyTobagoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTrinidadyTobagoMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TRINIDAD Y TOBAGO");

        javax.swing.GroupLayout jPanelTrinidadyTobagoLayout = new javax.swing.GroupLayout(jPanelTrinidadyTobago);
        jPanelTrinidadyTobago.setLayout(jPanelTrinidadyTobagoLayout);
        jPanelTrinidadyTobagoLayout.setHorizontalGroup(
            jPanelTrinidadyTobagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrinidadyTobagoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelTrinidadyTobagoLayout.setVerticalGroup(
            jPanelTrinidadyTobagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrinidadyTobagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSantaLucia.setBackground(new java.awt.Color(55, 55, 55));
        jPanelSantaLucia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSantaLuciaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSantaLuciaMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SANTA LUCIA");

        javax.swing.GroupLayout jPanelSantaLuciaLayout = new javax.swing.GroupLayout(jPanelSantaLucia);
        jPanelSantaLucia.setLayout(jPanelSantaLuciaLayout);
        jPanelSantaLuciaLayout.setHorizontalGroup(
            jPanelSantaLuciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSantaLuciaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSantaLuciaLayout.setVerticalGroup(
            jPanelSantaLuciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSantaLuciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBarbados.setBackground(new java.awt.Color(55, 55, 55));
        jPanelBarbados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBarbadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBarbadosMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BARBADOS");

        javax.swing.GroupLayout jPanelBarbadosLayout = new javax.swing.GroupLayout(jPanelBarbados);
        jPanelBarbados.setLayout(jPanelBarbadosLayout);
        jPanelBarbadosLayout.setHorizontalGroup(
            jPanelBarbadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarbadosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBarbadosLayout.setVerticalGroup(
            jPanelBarbadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarbadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanelGranada.setBackground(new java.awt.Color(55, 55, 55));
        jPanelGranada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGranadaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelGranadaMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GRANADA");

        javax.swing.GroupLayout jPanelGranadaLayout = new javax.swing.GroupLayout(jPanelGranada);
        jPanelGranada.setLayout(jPanelGranadaLayout);
        jPanelGranadaLayout.setHorizontalGroup(
            jPanelGranadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGranadaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGranadaLayout.setVerticalGroup(
            jPanelGranadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGranadaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanelIslasTurcasyCaicos.setBackground(new java.awt.Color(55, 55, 55));
        jPanelIslasTurcasyCaicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelIslasTurcasyCaicosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelIslasTurcasyCaicosMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ISLAS TURCAS Y CAICOS");

        javax.swing.GroupLayout jPanelIslasTurcasyCaicosLayout = new javax.swing.GroupLayout(jPanelIslasTurcasyCaicos);
        jPanelIslasTurcasyCaicos.setLayout(jPanelIslasTurcasyCaicosLayout);
        jPanelIslasTurcasyCaicosLayout.setHorizontalGroup(
            jPanelIslasTurcasyCaicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIslasTurcasyCaicosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIslasTurcasyCaicosLayout.setVerticalGroup(
            jPanelIslasTurcasyCaicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIslasTurcasyCaicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanelIslasCaiman.setBackground(new java.awt.Color(55, 55, 55));
        jPanelIslasCaiman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelIslasCaimanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelIslasCaimanMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ISLAS CAIMAN");

        javax.swing.GroupLayout jPanelIslasCaimanLayout = new javax.swing.GroupLayout(jPanelIslasCaiman);
        jPanelIslasCaiman.setLayout(jPanelIslasCaimanLayout);
        jPanelIslasCaimanLayout.setHorizontalGroup(
            jPanelIslasCaimanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIslasCaimanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIslasCaimanLayout.setVerticalGroup(
            jPanelIslasCaimanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIslasCaimanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanelRepublicaDominicana.setBackground(new java.awt.Color(55, 55, 55));
        jPanelRepublicaDominicana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRepublicaDominicanaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRepublicaDominicanaMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("REPUBLICA DOMINICANA");

        javax.swing.GroupLayout jPanelRepublicaDominicanaLayout = new javax.swing.GroupLayout(jPanelRepublicaDominicana);
        jPanelRepublicaDominicana.setLayout(jPanelRepublicaDominicanaLayout);
        jPanelRepublicaDominicanaLayout.setHorizontalGroup(
            jPanelRepublicaDominicanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepublicaDominicanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRepublicaDominicanaLayout.setVerticalGroup(
            jPanelRepublicaDominicanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepublicaDominicanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSanVicenteyLasGRN.setBackground(new java.awt.Color(55, 55, 55));
        jPanelSanVicenteyLasGRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSanVicenteyLasGRNMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSanVicenteyLasGRNMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SAN VICENTE Y LAS GRN");

        javax.swing.GroupLayout jPanelSanVicenteyLasGRNLayout = new javax.swing.GroupLayout(jPanelSanVicenteyLasGRN);
        jPanelSanVicenteyLasGRN.setLayout(jPanelSanVicenteyLasGRNLayout);
        jPanelSanVicenteyLasGRNLayout.setHorizontalGroup(
            jPanelSanVicenteyLasGRNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSanVicenteyLasGRNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(14, 14, 14))
        );
        jPanelSanVicenteyLasGRNLayout.setVerticalGroup(
            jPanelSanVicenteyLasGRNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSanVicenteyLasGRNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSanCristobalyNieves.setBackground(new java.awt.Color(55, 55, 55));
        jPanelSanCristobalyNieves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSanCristobalyNievesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSanCristobalyNievesMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SAN CRISTOBAL Y NIEVES");

        javax.swing.GroupLayout jPanelSanCristobalyNievesLayout = new javax.swing.GroupLayout(jPanelSanCristobalyNieves);
        jPanelSanCristobalyNieves.setLayout(jPanelSanCristobalyNievesLayout);
        jPanelSanCristobalyNievesLayout.setHorizontalGroup(
            jPanelSanCristobalyNievesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSanCristobalyNievesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSanCristobalyNievesLayout.setVerticalGroup(
            jPanelSanCristobalyNievesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSanCristobalyNievesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelIslasVirgenesBRT.setBackground(new java.awt.Color(55, 55, 55));
        jPanelIslasVirgenesBRT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelIslasVirgenesBRTMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelIslasVirgenesBRTMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ISLAS VIRGENES BRT");

        javax.swing.GroupLayout jPanelIslasVirgenesBRTLayout = new javax.swing.GroupLayout(jPanelIslasVirgenesBRT);
        jPanelIslasVirgenesBRT.setLayout(jPanelIslasVirgenesBRTLayout);
        jPanelIslasVirgenesBRTLayout.setHorizontalGroup(
            jPanelIslasVirgenesBRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIslasVirgenesBRTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(22, 22, 22))
        );
        jPanelIslasVirgenesBRTLayout.setVerticalGroup(
            jPanelIslasVirgenesBRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIslasVirgenesBRTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAnguila.setBackground(new java.awt.Color(55, 55, 55));
        jPanelAnguila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAnguilaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelAnguilaMousePressed(evt);
            }
        });
        jPanelAnguila.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanelAnguilaKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ANGUILA");

        javax.swing.GroupLayout jPanelAnguilaLayout = new javax.swing.GroupLayout(jPanelAnguila);
        jPanelAnguila.setLayout(jPanelAnguilaLayout);
        jPanelAnguilaLayout.setHorizontalGroup(
            jPanelAnguilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnguilaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAnguilaLayout.setVerticalGroup(
            jPanelAnguilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnguilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBahamas.setBackground(new java.awt.Color(55, 55, 55));
        jPanelBahamas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBahamasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBahamasMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("BAHAMAS");

        javax.swing.GroupLayout jPanelBahamasLayout = new javax.swing.GroupLayout(jPanelBahamas);
        jPanelBahamas.setLayout(jPanelBahamasLayout);
        jPanelBahamasLayout.setHorizontalGroup(
            jPanelBahamasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBahamasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBahamasLayout.setVerticalGroup(
            jPanelBahamasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBahamasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAntiguayBarbuda.setBackground(new java.awt.Color(55, 55, 55));
        jPanelAntiguayBarbuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAntiguayBarbudaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelAntiguayBarbudaMousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ANTIGUA Y BARBUDA");

        javax.swing.GroupLayout jPanelAntiguayBarbudaLayout = new javax.swing.GroupLayout(jPanelAntiguayBarbuda);
        jPanelAntiguayBarbuda.setLayout(jPanelAntiguayBarbudaLayout);
        jPanelAntiguayBarbudaLayout.setHorizontalGroup(
            jPanelAntiguayBarbudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAntiguayBarbudaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAntiguayBarbudaLayout.setVerticalGroup(
            jPanelAntiguayBarbudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAntiguayBarbudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMontserrat.setBackground(new java.awt.Color(55, 55, 55));
        jPanelMontserrat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMontserratMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelMontserratMousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("MONTSERRAT");

        javax.swing.GroupLayout jPanelMontserratLayout = new javax.swing.GroupLayout(jPanelMontserrat);
        jPanelMontserrat.setLayout(jPanelMontserratLayout);
        jPanelMontserratLayout.setHorizontalGroup(
            jPanelMontserratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMontserratLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMontserratLayout.setVerticalGroup(
            jPanelMontserratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMontserratLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAllSIPTrunks.setBackground(new java.awt.Color(55, 55, 55));
        jPanelAllSIPTrunks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAllSIPTrunksMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelAllSIPTrunksMousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("All SIP Trunks");

        javax.swing.GroupLayout jPanelAllSIPTrunksLayout = new javax.swing.GroupLayout(jPanelAllSIPTrunks);
        jPanelAllSIPTrunks.setLayout(jPanelAllSIPTrunksLayout);
        jPanelAllSIPTrunksLayout.setHorizontalGroup(
            jPanelAllSIPTrunksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllSIPTrunksLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAllSIPTrunksLayout.setVerticalGroup(
            jPanelAllSIPTrunksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllSIPTrunksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTrunkID.setBackground(new java.awt.Color(55, 55, 55));
        jPanelTrunkID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTrunkIDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTrunkIDMousePressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Trunk ID");

        javax.swing.GroupLayout jPanelTrunkIDLayout = new javax.swing.GroupLayout(jPanelTrunkID);
        jPanelTrunkID.setLayout(jPanelTrunkIDLayout);
        jPanelTrunkIDLayout.setHorizontalGroup(
            jPanelTrunkIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrunkIDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(50, 50, 50))
        );
        jPanelTrunkIDLayout.setVerticalGroup(
            jPanelTrunkIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrunkIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTeams.setBackground(new java.awt.Color(55, 55, 55));
        jPanelTeams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTeamsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTeamsMousePressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Teams");

        javax.swing.GroupLayout jPanelTeamsLayout = new javax.swing.GroupLayout(jPanelTeams);
        jPanelTeams.setLayout(jPanelTeamsLayout);
        jPanelTeamsLayout.setHorizontalGroup(
            jPanelTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTeamsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(58, 58, 58))
        );
        jPanelTeamsLayout.setVerticalGroup(
            jPanelTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCMS.setBackground(new java.awt.Color(55, 55, 55));
        jPanelCMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCMSMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCMSMousePressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("CMS");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCMSLayout = new javax.swing.GroupLayout(jPanelCMS);
        jPanelCMS.setLayout(jPanelCMSLayout);
        jPanelCMSLayout.setHorizontalGroup(
            jPanelCMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCMSLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel25)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanelCMSLayout.setVerticalGroup(
            jPanelCMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCMSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIslasTurcasyCaicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelGranada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBarbados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSantaLucia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelTrinidadyTobago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelJamaica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelIslasCaiman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRepublicaDominicana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSanVicenteyLasGRN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSanCristobalyNieves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelIslasVirgenesBRT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAnguila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBahamas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAntiguayBarbuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMontserrat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAllSIPTrunks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTrunkID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTeams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelJamaica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTrinidadyTobago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSantaLucia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBarbados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGranada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelIslasTurcasyCaicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelIslasCaiman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRepublicaDominicana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSanVicenteyLasGRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSanCristobalyNieves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelIslasVirgenesBRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAnguila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBahamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAntiguayBarbuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMontserrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAllSIPTrunks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelCMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTrunkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPanel)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPanel)
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelJamaicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJamaicaMousePressed
        jPanelJamaica.setBackground(ClickedColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Jamaica");
    }//GEN-LAST:event_jPanelJamaicaMousePressed

    private void jPanelTrinidadyTobagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTrinidadyTobagoMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(ClickedColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Trinididad y Tobago");
    }//GEN-LAST:event_jPanelTrinidadyTobagoMousePressed

    private void jPanelSantaLuciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSantaLuciaMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(ClickedColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Santa Lucia");
    }//GEN-LAST:event_jPanelSantaLuciaMousePressed

    private void jPanelBarbadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarbadosMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(ClickedColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Barbados");
    }//GEN-LAST:event_jPanelBarbadosMousePressed

    private void jPanelGranadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGranadaMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(ClickedColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Granada");
    }//GEN-LAST:event_jPanelGranadaMousePressed

    private void jPanelIslasTurcasyCaicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIslasTurcasyCaicosMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(ClickedColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Islas Turcas y Caicos");
    }//GEN-LAST:event_jPanelIslasTurcasyCaicosMousePressed

    private void jPanelIslasCaimanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIslasCaimanMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(ClickedColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Islas Caiman");
    }//GEN-LAST:event_jPanelIslasCaimanMousePressed

    private void jPanelRepublicaDominicanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRepublicaDominicanaMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(ClickedColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanel.setBackground(DefaultColor);

        CiudadName.setText("Republica Dominiana");
    }//GEN-LAST:event_jPanelRepublicaDominicanaMousePressed

    private void jPanelSanVicenteyLasGRNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSanVicenteyLasGRNMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(ClickedColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("San Viente y las Granadinas");
    }//GEN-LAST:event_jPanelSanVicenteyLasGRNMousePressed

    private void jPanelSanCristobalyNievesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSanCristobalyNievesMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(ClickedColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("San Cristobal y Nieves");
    }//GEN-LAST:event_jPanelSanCristobalyNievesMousePressed

    private void jPanelIslasVirgenesBRTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIslasVirgenesBRTMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(ClickedColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Islas Virgenes Britanicas");
    }//GEN-LAST:event_jPanelIslasVirgenesBRTMousePressed

    private void jPanelAnguilaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAnguilaMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(ClickedColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Anguila");
    }//GEN-LAST:event_jPanelAnguilaMousePressed

    private void jPanelBahamasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBahamasMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(ClickedColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Bahamas");
    }//GEN-LAST:event_jPanelBahamasMousePressed

    private void jPanelAntiguayBarbudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAntiguayBarbudaMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(ClickedColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Antigua y Barbuda");
    }//GEN-LAST:event_jPanelAntiguayBarbudaMousePressed

    private void jPanelMontserratMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMontserratMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(ClickedColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Montserrat");
    }//GEN-LAST:event_jPanelMontserratMousePressed

    private void jPanelAllSIPTrunksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAllSIPTrunksMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(ClickedColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("All SIP Trunk");
    }//GEN-LAST:event_jPanelAllSIPTrunksMousePressed

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed

    }//GEN-LAST:event_jLabel25MousePressed

    private void jPanelTrunkIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTrunkIDMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(ClickedColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("Trunk ID");
    }//GEN-LAST:event_jPanelTrunkIDMousePressed

    private void jPanelCMSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCMSMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(ClickedColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("CMS");
    }//GEN-LAST:event_jPanelCMSMousePressed

    private void jPanelTeamsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTeamsMousePressed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(ClickedColor);

        CiudadName.setText("Teams");
    }//GEN-LAST:event_jPanelTeamsMousePressed

    private void jPanelJamaicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelJamaicaMouseClicked
        IntFrmJamaica intfrmjamaica = new IntFrmJamaica();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmjamaica).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelJamaicaMouseClicked

    private void jPanelTrinidadyTobagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTrinidadyTobagoMouseClicked
        IntFrmTrinidadyTobago intfrmtrinidadytobago = new IntFrmTrinidadyTobago();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmtrinidadytobago).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelTrinidadyTobagoMouseClicked

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        jPanelJamaica.setBackground(DefaultColor);
        jPanelTrinidadyTobago.setBackground(DefaultColor);
        jPanelSantaLucia.setBackground(DefaultColor);
        jPanelBarbados.setBackground(DefaultColor);
        jPanelGranada.setBackground(DefaultColor);
        jPanelIslasTurcasyCaicos.setBackground(DefaultColor);
        jPanelIslasCaiman.setBackground(DefaultColor);
        jPanelRepublicaDominicana.setBackground(DefaultColor);
        jPanelSanVicenteyLasGRN.setBackground(DefaultColor);
        jPanelSanCristobalyNieves.setBackground(DefaultColor);
        jPanelIslasVirgenesBRT.setBackground(DefaultColor);
        jPanelAnguila.setBackground(DefaultColor);
        jPanelBahamas.setBackground(DefaultColor);
        jPanelAntiguayBarbuda.setBackground(DefaultColor);
        jPanelMontserrat.setBackground(DefaultColor);
        jPanelAllSIPTrunks.setBackground(DefaultColor);
        jPanelCMS.setBackground(DefaultColor);
        jPanelTrunkID.setBackground(DefaultColor);
        jPanelTeams.setBackground(DefaultColor);

        CiudadName.setText("...");

        jDesktopPanel.removeAll();
        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void jPanelSantaLuciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSantaLuciaMouseClicked
        IntFrmSantaLucia intfrmsantalucia = new IntFrmSantaLucia();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmsantalucia).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelSantaLuciaMouseClicked

    private void jPanelBarbadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarbadosMouseClicked
        IntFrmBarbados intfrmbarbados = new IntFrmBarbados();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmbarbados).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelBarbadosMouseClicked

    private void jPanelGranadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGranadaMouseClicked
        IntFrmGranada intfrmgranada = new IntFrmGranada();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmgranada).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelGranadaMouseClicked

    private void jPanelIslasTurcasyCaicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIslasTurcasyCaicosMouseClicked
        IntFrmIslasTurcasyCaicos intfrmislasturcasycaicos = new IntFrmIslasTurcasyCaicos();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmislasturcasycaicos).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelIslasTurcasyCaicosMouseClicked

    private void jPanelIslasCaimanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIslasCaimanMouseClicked
        IntFrmIslasCaiman intfrmislascaiman = new IntFrmIslasCaiman();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmislascaiman).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelIslasCaimanMouseClicked

    private void BtnSIPMEDIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSIPMEDIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSIPMEDIAActionPerformed

    private void jPanelRepublicaDominicanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRepublicaDominicanaMouseClicked
        IntFrmRepublicaDominicana intfrmrepublicadominicana = new IntFrmRepublicaDominicana();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmrepublicadominicana).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelRepublicaDominicanaMouseClicked

    private void jPanelSanVicenteyLasGRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSanVicenteyLasGRNMouseClicked
        IntFrmSanVicenteyLasGRN intfrmsanvicenteylasgrn = new IntFrmSanVicenteyLasGRN();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmsanvicenteylasgrn).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelSanVicenteyLasGRNMouseClicked

    private void jPanelSanCristobalyNievesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSanCristobalyNievesMouseClicked
        IntFrmSanCristobalyNieves intfrmsancristobalynieves = new IntFrmSanCristobalyNieves();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmsancristobalynieves).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelSanCristobalyNievesMouseClicked

    private void jPanelIslasVirgenesBRTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIslasVirgenesBRTMouseClicked
        IntFrmIslasVirgenesBritanicas intfrmislasvirgenesbritanicas = new IntFrmIslasVirgenesBritanicas();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmislasvirgenesbritanicas).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelIslasVirgenesBRTMouseClicked

    private void jPanelAnguilaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelAnguilaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAnguilaKeyPressed

    private void jPanelAnguilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAnguilaMouseClicked
        IntFrmAnguila intfrmanguila = new IntFrmAnguila();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmanguila).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelAnguilaMouseClicked

    private void jPanelBahamasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBahamasMouseClicked
        IntFrmBahamas intfrmbahamas = new IntFrmBahamas();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmbahamas).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelBahamasMouseClicked

    private void jPanelAntiguayBarbudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAntiguayBarbudaMouseClicked
        IntFrmAntiguayBarbuda intfrmantiguaybarbuda = new IntFrmAntiguayBarbuda();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmantiguaybarbuda).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelAntiguayBarbudaMouseClicked

    private void jPanelMontserratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMontserratMouseClicked
        IntFrmMontserrat intfrmmontserrat = new IntFrmMontserrat();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmmontserrat).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelMontserratMouseClicked

    private void jPanelAllSIPTrunksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAllSIPTrunksMouseClicked
        IntFrmAllSIPTrunks intfrmallsiptrunks = new IntFrmAllSIPTrunks();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmallsiptrunks).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelAllSIPTrunksMouseClicked

    private void jPanelCMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCMSMouseClicked
        IntFrmCMS intfrmcms = new IntFrmCMS();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmcms).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelCMSMouseClicked

    private void jPanelTrunkIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTrunkIDMouseClicked
        IntFrmTrunkID intfrmtrunkid = new IntFrmTrunkID();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmtrunkid).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelTrunkIDMouseClicked

    private void jPanelTeamsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTeamsMouseClicked
        IntFrmTeams intfrmteams = new IntFrmTeams();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmteams).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_jPanelTeamsMouseClicked

    private void BtnVirtualRangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVirtualRangesActionPerformed
        IntFrmVirtualRanges intfrmvirtualranges = new IntFrmVirtualRanges();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmvirtualranges).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_BtnVirtualRangesActionPerformed

    private void BtnSIPMEDIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSIPMEDIAMouseClicked
        IntFrmSIPMedia intfrmsipmedia = new IntFrmSIPMedia();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmsipmedia).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_BtnSIPMEDIAMouseClicked

    private void BtnVoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVoiceMouseClicked
        IntFrmVoice intfrmvoice = new IntFrmVoice();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(intfrmvoice).setVisible(true);

        jDesktopPanel.revalidate();
        jDesktopPanel.repaint();
    }//GEN-LAST:event_BtnVoiceMouseClicked

    private void BtnVirtualRangesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVirtualRangesMousePressed
        CiudadName.setText("Virtual Ranges");
    }//GEN-LAST:event_BtnVirtualRangesMousePressed

    private void BtnSIPMEDIAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSIPMEDIAMousePressed
        CiudadName.setText("SIP & Media Addresess");
    }//GEN-LAST:event_BtnSIPMEDIAMousePressed

    private void BtnVoiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVoiceMousePressed
        CiudadName.setText("Voice GW");
    }//GEN-LAST:event_BtnVoiceMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel labelName, String path) {

        java.net.URL url = getClass().getResource(path);
        if (url == null) {
            System.out.println("No se encontró: " + path);
            return;
        }

        ImageIcon image = new ImageIcon(url);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSIPMEDIA;
    private javax.swing.JButton BtnVirtualRanges;
    private javax.swing.JButton BtnVoice;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel CiudadName;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAllSIPTrunks;
    private javax.swing.JPanel jPanelAnguila;
    private javax.swing.JPanel jPanelAntiguayBarbuda;
    private javax.swing.JPanel jPanelBahamas;
    private javax.swing.JPanel jPanelBarbados;
    private javax.swing.JPanel jPanelCMS;
    private javax.swing.JPanel jPanelGranada;
    private javax.swing.JPanel jPanelIslasCaiman;
    private javax.swing.JPanel jPanelIslasTurcasyCaicos;
    private javax.swing.JPanel jPanelIslasVirgenesBRT;
    private javax.swing.JPanel jPanelJamaica;
    private javax.swing.JPanel jPanelMontserrat;
    private javax.swing.JPanel jPanelRepublicaDominicana;
    private javax.swing.JPanel jPanelSanCristobalyNieves;
    private javax.swing.JPanel jPanelSanVicenteyLasGRN;
    private javax.swing.JPanel jPanelSantaLucia;
    private javax.swing.JPanel jPanelTeams;
    private javax.swing.JPanel jPanelTrinidadyTobago;
    private javax.swing.JPanel jPanelTrunkID;
    // End of variables declaration//GEN-END:variables
}
