/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author gabri
 */
public class IntFrmSIPMedia extends javax.swing.JInternalFrame {

    /**
     * Creates new form IntFrmJamaica
     */
    public IntFrmSIPMedia() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBorder(null);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        jTextField1.setText("Buscador de SIP Media");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, java.awt.BorderLayout.PAGE_START);

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "10.235.115.237 ", "10.235.115.230 ", "10.235.115.238 ", "10.235.115.233 ", "172.31.21.162  ", "172.31.21.162  ", "172.31.21.163  "},
                {"Turks and Caicos  ", null, "10.235.115.231 ", null, "10.235.115.234 ", null, null, null},
                {"Bahamas ", "10.223.254.68 (Nassau) ", null, "10.223.254.69 (Nassau) ", null, "172.31.21.162  ", "172.31.21.162  ", "173.31.21.163  "},
                {null, "10.223.254.4 (Freeport) ", null, null, null, null, null, null}
            },
            new String [] {
                "", "MyUC Signaling IP", "MyUC Media IP", "BT Signaling IP", "BT Media IP", "DNS MyUC", "NTP MyUC", "Provisioning IP MyUC"
            }
        ));
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("MyUC Signaling IP");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("MyUC Media IP");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("BT Signaling IP");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("BT Media IP");
            jTable2.getColumnModel().getColumn(5).setHeaderValue("DNS MyUC");
            jTable2.getColumnModel().getColumn(6).setHeaderValue("NTP MyUC");
            jTable2.getColumnModel().getColumn(7).setHeaderValue("Provisioning IP MyUC");
        }

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
