/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author gabri
 */
public class IntFrmVirtualRanges extends javax.swing.JInternalFrame {

    /**
     * Creates new form IntFrmJamaica
     */
    public IntFrmVirtualRanges() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBorder(null);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        jTextField1.setText("Buscador de Virtual Ranges");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, java.awt.BorderLayout.PAGE_START);

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"(833)999 ", "Grenada "},
                {"(833)999 ", "KY "},
                {"(833)999 ", "TTO "},
                {"(833)999 ", "Grenada "},
                {"(834)999 ", "Barbados "},
                {"(834)999 ", "Barbados "},
                {"(835)999 ", "Puerto Rico "},
                {"(836)000 ", "JAM "},
                {"(836)000 ", "JAM "},
                {"(837)77 ", "JAM "},
                {"(837)998 ", "TTO "},
                {"(837)999 ", "TTO "},
                {"(838)999 ", "RepDominicana"},
                {"(838)999 ", "RepDominicana"},
                {"(834)995 ", "Bahamas"}
            },
            new String [] {
                "#", "CTY"
            }
        ));
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
